### ISSUE TITLE
Linker corrupts PDBs Metadata header id which makes it not to match Assembly Id any longer

### ISSUE THREAD

**Issue by joperezr** [mono/linker#1285] opened 2020-06-19 22:52 UTC
cc: @sbomer @eerhardt 

Say you have a very simple console app with the following code:
```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        StackTrace thisTrace = new StackTrace(fNeedFileInfo: true);

        if (thisTrace.GetFrame(thisTrace.FrameCount - 1).GetFileLineNumber() == 0)
        {
            throw new Exception("Unable to retrieve line info");
        }
    }
}
```

This will work just fine if you try to run it in a self contained app, but if you pass in `/p:PublishTrimmed=true` then it will start throwing an exception. The reason is that after the linker trims the assembly and the PDB, StackTrace constructor will fail to find PDBs for the console app, particularly it will cause Metadata reader to fail this check: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L828-L832

```c#
                // Validate that the PDB matches the assembly version
                if (new BlobContentId(candidate.GetMetadataReader().DebugMetadataHeader!.Id) != id)
                {
                    return false;
                }
```
as that if check will find that the PDB doesn't match the assembly version any longer and the method body will return false, meaning a metadata provider won't be succesfully returned.

**Comment by eerhardt** [comment] 2020-06-19 23:04
cc @vitek-karas as well, since he's been looking into other PDB issues.

**Comment by sbomer** [comment] 2020-06-19 23:39
This looks like the issue(s) I had started fixing in https://github.com/dotnet/sdk/pull/11458/files:
- the defaults don't link symbols (fix by passing `-b` or setting `_TrimmerLinkSymbols`)
- even when symbols are linked, the publish logic doesn't place linked symbols into the correct output directory - I think this is a regression introduced by https://github.com/dotnet/sdk/commit/84f017cbfd818ab3d1e5220e48703f5180478122.

I just confirmed that placing the linked pdb into the publish directory results in no exception thrown by your testcase.

**Comment by joperezr** [comment] 2020-06-20 00:21
I did notice that the app was trying to get the pdbs from the obj\linked directory but the path looked right so I would have imagined that the test case should still pass. If the problem is only where the pdb is placed, then I'm not sure I understand why does the Id does not match on the above line I pointed out from the PEReader.

**Comment by sbomer** [comment] 2020-07-01 18:49
This will be fixed by https://github.com/dotnet/sdk/pull/12144. I double-checked the behavior of the Id - here's what I see:
- The `linked` directory gets a dll and pdb with matching `Id`.
- Before the fix, the linked dll gets copied, but the pre-linked pdb (with different `Id`) gets copied to the publish directory

That might explain the behavior @joperezr saw with mismatching `Id`s. I didn't ever see the PDB picked up directly from the `linked` directory, only the `publish` directory, so there may be some setup difference that caused the problem to manifest a bit differently, but I believe it is fixed.

The only remaining issue I'm aware of is that `.ni.pdb` files are not looked for by the linker. I think we should not fix this since it sounds like we're moving to prefer the plain `pdb` extension for all PDBs. I also checked that `PublishReadyToRun` outputs PDBs with the `pdb` extension only - and that when using `PublishReadyToRun` with `PublishTrimmed`, the output dll and PDB have matching `Id` (after the fix above).

**Comment by joperezr** [comment] 2020-07-01 22:29
Once you have an sdk with this change I'm happy to test locally to see if the issue I was seeing goes away

**Comment by vitek-karas** [comment] 2020-07-07 12:31
It's been 5 days since the fix has been merged. Is it possible to verify the fix now?

**Comment by sbomer** [comment] 2020-07-07 16:09
Still waiting for dependency flow - not sure why it is taking so long, but https://github.com/dotnet/installer/pull/7943 will bring in the change.

**Comment by sbomer** [comment] 2020-07-09 16:41
@joperezr the change has made it into the latest bits - would you mind giving it a try?

**Comment by sbomer** [comment] 2020-07-13 16:37
Closing this since the fix was confirmed for the similar https://github.com/mono/linker/issues/1331. @joperezr if you are still able to reproduce this, please reopen. Thanks!

**Closed by sbomer** 2020-07-13 16:37 UTC
Labels: area-Integration: netcore
