### ISSUE TITLE
ILLink : error IL1012 when running a build on a build server

### ISSUE THREAD

**Issue by git-hub-user** [mono/linker#2007] opened 2021-04-30 17:24 UTC
We are using a Jenkins build server with a Windows Slave to build and deploy a .Net core 3.1 web application.

Since a couple of days, we have an issue with the build.
Command:
```
dotnet publish --verbosity minimal <removed>.csproj /p:PublishProfile=${params.PUBLISH_PROFILE} -c Release -r win-x64 /p:Password=${params.IIS_PASS}
```
Output:
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [<removed>.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
     at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
     at System.Text.RegularExpressions.Regex.Matches(String input)
     at Mono.Linker.Steps.MarkStep.MarkTypeWithDebuggerDisplayAttribute(TypeDefinition type, CustomAttribute attribute)
     at Mono.Linker.Steps.MarkStep.MarkTypeSpecialCustomAttributes(TypeDefinition type)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\5.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [<removed>.csproj]
```
The project has TargetFramework netcoreapp3.1.

There were no apparent significant changes to the projects before the build started to fail, like changes to referenced assemblies. But, in the mean time, the following was installed on the build server:
-     .Net SDK 5.0.202 (x64)
-     Microsoft .Net Runtime - 5.0.0 (x86)
-     Microsoft .Net Runtime - 5.0.0 (x64)
-     Microsoft .Net Core 5.0.0 - Windows Server Hosting

Notably, another build also failed, which builds the assemblies to perform unit tests. It reported;
```
Testhost process exited with error: Error:
  An assembly specified in the application dependencies manifest (<removed>.deps.json) was not found:
    package: 'Microsoft.Data.SqlClient', version: '1.1.3'
    path: 'runtimes/win/lib/netcoreapp2.1/Microsoft.Data.SqlClient.dll'
```
This is in another project, but might be related. This issue went away after Installed some .Net core runtimes:
-     .Net Core Runtime - 2.1.26 (x86)
-     .Net Core Runtime - 2.1.26 (x64)
-     .Net Core Runtime - 3.1.13 (x86)
-     .Net Core Runtime - 3.1.13 (x64)

**Comment by marek-safar** [comment] 2021-04-30 17:50
This is a duplicate of #1648.

**Closed by marek-safar** 2021-04-30 17:50 UTC
