### ISSUE TITLE
WPF app does not publish with error "IL Linker has encountered an unexpected error"

### ISSUE THREAD

**Issue by ansarnisargill** [mono/linker#1653] opened 2020-11-27 08:54 UTC
I have WPF app targeting **net5.0-windows10.0.19041.0**. When I publish it using **Trim Unused Assemblies** option, IL Linker throws **Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.**
I can't seem to place the origin of the exception. Here is complete stack trace for this issue:

```
3>IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
3>Fatal error in IL Linker
3>Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
3>   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.GetValueNodeFromGenericArgument(TypeReference genericArgument)
3>   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ProcessGenericArgumentDataFlow(GenericParameter genericParameter, TypeReference genericArgument, IMemberDefinition source)
3>   at Mono.Linker.Steps.MarkStep.MarkGenericArgumentConstructors(IGenericInstance instance, IMemberDefinition sourceLocationMember)
3>   at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance, IMemberDefinition sourceLocationMember)
3>   at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type, DependencyInfo reason, IMemberDefinition sourceLocationMember)
3>   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
3>   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
3>   at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
3>   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
3>   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
3>   at Mono.Linker.Steps.MarkStep.Initialize()
3>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
3>   at Mono.Linker.Pipeline.Process(LinkContext context)
3>   at Mono.Linker.Driver.Run(ILogger customLogger)
3>   at Mono.Linker.Driver.Main(String[] args)
```

**Comment by marek-safar** [comment] 2020-11-27 16:34
Duplicate of #1634

**Closed by marek-safar** 2020-11-27 16:34 UTC
