### ISSUE TITLE
RUC analyzer does not warn about delegate conversion

### ISSUE THREAD

**Issue by agocke** [mono/linker#1912] opened 2021-03-23 03:10 UTC
E.g.

```C#
[RequiresUnreferencedCode("")]
void M1() { }
void M2()
{
    Action a = M1; // should warn
    Action b = () => M1(); // should warn
}
```

**Comment by MichalStrehovsky** [comment] 2021-03-23 12:10
Dupe of #1764? "We should probably extend this to delegates pointing to such methods (although that one has a natural extension - we could require the delegate invoke method itself to be annotated same as the target)."

**Comment by agocke** [comment] 2021-03-23 18:06
Yeah, they're maybe dups -- this bug was specific to the analyzer, but if the linker is missing similar analysis it makes sense to do both together. 

My suggestion is simpler as well-- warn at the point of delegate conversion, instead of Invoke, so we don't have to do alias tracking for delegate instances. From what I've seen it's often not a worse experience anyway because users often want to see the origination of the problem instead of the final invocation.

**Comment by MichalStrehovsky** [comment] 2021-03-23 18:58
> My suggestion is simpler as well-- warn at the point of delegate conversion, instead of Invoke

Yup, this is also what I want linker to do. The comment about invoke method is just that we could potentially allow delegate conversion if the delegate itself has matching annotations. So for example:

```csharp
delegate ConstructorInfo GimmeConstructor([DynamicallyAccessedMembers(Constructors)] Type theType);
```

Could be used to construct a delegate pointing to an annotated method. The annotations at the delegate use site naturally fall out.

Unfortunately, it doesn't look like C# allows placing attributes on the Invoke method itself, so the natural extension for RequiresUnreferencedCode doesn't look possible. But it could work at least for the flow annotations if we have the need.

**Comment by tlakollo** [comment] 2021-07-01 19:03
While reviewing the tests and adding some more for RAF I realized that both Linker and Analyzer already have support for this so I will close this PR and add lazy tests in #2113

**Closed by tlakollo** 2021-07-01 19:03 UTC
