### ISSUE TITLE
DynamicDependencyAttribute.Condition and Feature Switches

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1231] opened 2020-06-01 22:31 UTC
The `DynamicDependencyAttribute` has a `string Condition` property:

https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/DynamicDependencyAttribute.cs#L126-L129

```C#
        /// <summary>
        /// Gets or sets the condition in which the dependency is applicable, e.g. "DEBUG".
        /// </summary>
        public string? Condition { get; set; }
```

However, to my knowledge the linker only supports a hard-coded `DEBUG` condition:

https://github.com/mono/linker/blob/71c8e5d31649f42c63f7815dc4d5b88abcc8e759/src/linker/Linker.Steps/MarkStep.cs#L589-L602

We should allow [feature switches](https://github.com/dotnet/designs/blob/master/accepted/2020/feature-switch.md) to work with the Condition string in DynamicDependency.

An example of where this would be useful is in https://github.com/dotnet/runtime/issues/34910. Here we could put a `Condition="!System.Diagnostics.DebugMode.None"` on the attributes on the `internal void InitializeSourceInfo` method. This would mean to only preserve this dependency if the `System.Diagnostics.DebugMode.None` feature switch was off. When the `System.Diagnostics.DebugMode.None` feature switch is on, the dependency shouldn't be preserved.

cc @vitek-karas @marek-safar @sbomer @MichalStrehovsky

**Comment by marek-safar** [comment] 2020-06-02 15:53
You can consider "DEBUG" to be a hack to illustrate what this was intended for. I agree it should support feature switches but we need to define the relationship first because if bind it to feature switches only then we'd need to create feature switch for any condition which seem quite limiting to me.

**Comment by marek-safar** [comment] 2020-11-13 15:53
I'll close this as we took different approach

**Closed by marek-safar** 2020-11-13 15:53 UTC
Labels: task
