### ISSUE TITLE
Unresolvable type cases InvalidOperationException in ReflectionMethodBodyScanner.GetValueNodeFromGenericArgument

### ISSUE THREAD

**Issue by pranavkm** [mono/linker#1500] opened 2020-09-19 17:49 UTC
* Repro steps: Clone https://github.com/pranavkm/OAT
* cd OAT.Blazor
* dotnet publish

```C#
ILLink : error IL1005: Blazor.FileReader.SetupExtension.AddFileReaderService(IServiceCollection): Error processing method 'Blazor.FileReader.SetupExtension.AddFileReaderService(IServiceCollection)' in assembly 'Blazor.FileReader.Wasm.dll' [D:\temp\OAT\OAT.Blazor\OAT.Blazor.csproj]
  Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: Blazor.FileReader.SetupExtension.AddFileReaderService(IServiceCollection): Error processing method 'Blazor.FileReader.SetupExtension.AddFileReaderService(IServiceCollection)' in assembly 'Blazor.FileReader.Wasm.dll'
   ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.GetValueNodeFromGenericArgument(TypeReference genericArgument)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ProcessGenericArgumentDataFlow(GenericParameter genericParameter, TypeReference genericArgument, IMemberDefinition source)
     at Mono.Linker.Steps.MarkStep.MarkGenericArgumentConstructors(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.GetOriginalMethod(MethodReference method, DependencyInfo reason, IMemberDefinition sourceLocationMember)
```

Reproduced using SDK v5.0.100-rc.1.20452.10.

**Comment by marek-safar** [comment] 2020-09-20 09:25
@MichalStrehovsky could you investigate ?

**Comment by MichalStrehovsky** [comment] 2020-09-21 09:16
> @MichalStrehovsky could you investigate ?

I think @vitek-karas would be more up to speed on this.

**Comment by vitek-karas** [comment] 2020-09-21 10:22
There's a "failure" before this happens that linker can't resolve assembly `Blazor.FileReader`.
The failure itself is caused by an unresolvable type reference to `Blazor.FileReader.FileReaderService`. The project references assembly called `Tewr.Blazor.FileReader` which seem to contain all the right types, but the assembly names don't match.

As for linker, I need to figure out what is the correct way to handle unresolvable type references - linker should report a meaningful error and not what's effectively a "crash".

**Comment by gfs** [comment] 2020-09-21 15:26
@vitek-karas 

I tried with a default project with just blazor file reader and didn't encounter the same issue.

I also searched the OAT code for any referenced to "Blazor.FileReader" without "Tewr" and didn't find one.  Is there something in my configuration that is causing this or is it a linker issue?

**Comment by vitek-karas** [comment] 2020-10-07 12:25
The problem with this project is big mismatch in dependent NuGet package versions.
The `OAT.Blazor` project has a package reference to `Tewr.Blazor.FileReader.Wasm, version=0.11.19128`. This package has a dependency on `Tewr.Blazor.FileReader, version=0.11.19128`.
But the project `OAT.Blazor.Components` has a package reference to `Tewr.Blazor.FileReader, version=2.0.0.20242`.
So the whole solution ends up using `Tewr.Blazor.FileReader, version=2.0.0.20242`.
Apparently there's been assembly renames since the early versions of the `FileReader` and so the jump from `0.11.19128` to `2.0.0.20242` is a binary incompatible breaking change (due to assembly renames).

The assembly `Blazor.FileReader.Wasm, version=0.11.19128.0` has an assembly reference to `Blazor.FileReader` - which has been renamed to `Tewr.Blazor.FileReader`.

The `Tewr.Blazor.FileReader.Wasm` package is marked as deprecated and instead just the `Twer.Blazor.FileReader` should be used (according to https://www.nuget.org/packages/Tewr.Blazor.FileReader.Wasm/)

I'll leave this issue opened to fix the wrong exception in this case.

**Comment by marek-safar** [comment] 2020-11-26 09:48
Duplicate of #1634

**Closed by marek-safar** 2020-11-26 09:48 UTC
Labels: area-Linker: DataFlow, duplicate
