### ISSUE TITLE
Latest ILLink.Task is failing for osx-x64 Runtime Identifier

### ISSUE THREAD

**Issue by sidravi** [mono/linker#405] opened 2018-11-27 02:24 UTC
When I do `dotnet publish -c release -r osx-x64` after adding ILLink.Tasks nuget package version 0.1.5-preview-1841731, it fails with the following error: 
`C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(72,5): error NETSDK1016: Unable to find resolved path for '...\.nuget\packages\runtime.osx-x64.microsoft.netcore.app\2.1.6\runtimes\osx-x64\native\..\..\..\tools\crossgen.exe'. [....csproj]`

Looks like its searching for `crossgen.exe` for Mac version, instead of `crossgen`.

I tried using older versions (0.14 preview) and it failed with error `The "GetRuntimeLibraries" task failed unexpectedly.` I believe this is the same issue discussed in #308  which I think is resolved in later versions.

@sbomer

**Comment by GTANAdam** [comment] 2018-12-23 15:49
win-x64 and linux-x64 are affected as well, it seems that ILLink.Task is not compatible with netcoreapp2.2.

Error when publishing to 'linux-x64': 
> error NETSDK1016: Unable to find resolved path for 'coreclr'.

while publishing to 'win-x64':
>Fatal error in IL Linker
Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessReferences(AssemblyDefinition assembly, LinkContext context)
   at Mono.Linker.Steps.ResolveFromXmlStep.GetAssembly(LinkContext context, AssemblyNameReference assemblyName)
   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)`

**Comment by marek-safar** [comment] 2019-10-03 09:02
Duplicate of #286

**Closed by marek-safar** 2019-10-03 09:02 UTC
Labels: duplicate
