### ISSUE TITLE
Linker warnings should be outputted even without --verbose

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1184] opened 2020-05-12 23:07 UTC
When I run the linker against an assembly that has data flow analysis warnings, it won't tell me about those warnings unless I specify `--verbose`.

For example, we don't specify `--verbose` when linking the dotnet/runtime libraries: https://github.com/dotnet/runtime/blob/c23df5d2bcb027bd3944f29db97ed4a6bc20b988/eng/illink.targets#L82-L105, so we aren't getting any warnings for un-annotated use of Reflection.

We should decouple `--verbose` and the warnings. I don't want all the verbose output just to get the warnings.

cc @vitek-karas @marek-safar

**Comment by marek-safar** [comment] 2020-05-13 11:23
This is mostly duplicate of #1030

**Closed by marek-safar** 2020-05-13 11:23 UTC
Labels: duplicate
