### ISSUE TITLE
Linker failing in ASP.NET PlatformBenchmarks

### ISSUE THREAD

**Issue by agocke** [mono/linker#1663] opened 2020-12-02 18:01 UTC
```
dotnet publish PlatformBenchmarks.csproj -c Release -o /tmp/benchmarks-agent/benchmarks-server-1/srhuutcy.ceu/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/published /p:MicrosoftNETCoreAppPackageVersion=6.0.0-alpha.1.20601.6 /p:MicrosoftAspNetCoreAppPackageVersion=6.0.0-alpha.1.20601.10 /p:BenchmarksNETStandardImplicitPackageVersion=6.0.0-alpha.1.20601.10 /p:BenchmarksNETCoreAppImplicitPackageVersion=6.0.0-alpha.1.20601.10 /p:BenchmarksRuntimeFrameworkVersion=6.0.0-alpha.1.20601.6 /p:BenchmarksTargetFramework=net6.0 /p:BenchmarksAspNetCoreVersion=6.0.0-alpha.1.20601.10 /p:MicrosoftAspNetCoreAllPackageVersion=6.0.0-alpha.1.20601.10 /p:NETCoreAppMaximumVersion=99.9 /p:MicrosoftNETCoreApp50PackageVersion=6.0.0-alpha.1.20601.6 /p:GenerateErrorForMissingTargetingPacks=false /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App /p:RestoreNoCache=true /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:PublishTrimmed=true --framework net6.0 --self-contained -r linux-x64 
Microsoft (R) Build Engine version 16.9.0-preview-20561-01+56ab63409 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /tmp/benchmarks-agent/benchmarks-server-1/srhuutcy.ceu/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj (in 158 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  PlatformBenchmarks -> /tmp/benchmarks-agent/benchmarks-server-1/srhuutcy.ceu/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/bin/Release/net6.0/linux-x64/PlatformBenchmarks.dll
ILLink : error IL1005: System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate(): Error processing method 'System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate()' in assembly 'System.Private.DataContractSerialization.dll' [/tmp/benchmarks-agent/benchmarks-server-1/srhuutcy.ceu/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj]
  Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate(): Error processing method 'System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate()' in assembly 'System.Private.DataContractSerialization.dll'
   ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue)
     at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack)
     at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/tmp/benchmarks-agent/benchmarks-server-1/4xopky5v.fsc/sdk/6.0.100-alpha.1.20568.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(51,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/tmp/benchmarks-agent/benchmarks-server-1/srhuutcy.ceu/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj]
Exit code: 1
```

**Comment by agocke** [comment] 2020-12-02 18:03
I believe the repo is https://github.com/aspnet/Benchmarks

**Comment by vitek-karas** [comment] 2020-12-04 19:00
This was fixed in https://github.com/mono/linker/pull/1621
I'm trying to figure out why that fix (which is 23 days old) didn't make it into latest dotnet/installer (I can still repro the failure with latest SDK from 6.0 master, but not with latest linker from mono/linker).

**Comment by VSadov** [comment] 2020-12-09 18:12
It looks like SDK repo picked up dependencies from mono linker yesterday. 
@vitek-karas - could you check if this still reproduces in you setup?

**Comment by vitek-karas** [comment] 2020-12-09 19:05
I did verify that it works with current linker - for full verification we'll have to wait for SDK to make it into installer - which has been blocked for more than 2 weeks now.

**Comment by agocke** [comment] 2021-01-11 19:19
It looks like we've got a reasonably up-to-date version of runtime in `installer` now. Can we see if it still repros?

**Comment by vitek-karas** [comment] 2021-01-12 11:11
I verified that I can run the command line from the issue above (with R2R disabled, it doesn't allow me to use it - but that's not part of this issue) and it works just fine on `6.0.100-alpha.1.21060.3`. I'm closing this issue as resolved.

**Closed by vitek-karas** 2021-01-12 11:11 UTC
Labels: area-Linker: DataFlow
