### ISSUE TITLE
PublishTrimmed trims localization resources

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#764] opened 2019-09-26 17:41 UTC
Enabling `PublishTrimmed` results in some kind of corruption related to localization resources (resx) that are built as part of the project. I can see them included but they're much bigger than the non-trimmed versions, and they're stripped out of all strings.

Non-trimmed version properly displays localized strings depending on user's culture. Trimmed version displays only english strings, as if the resources were never bundled/compiled as part of `dotnet publish`.

It's nice to note that previously I've used latest version of `ILLink.Tasks` with the same project and I didn't suffer from this issue. It happened between `netcoreapp2.2` + `ILLink.Tasks` and `netcoreapp3.0` + `PublishTrimmed`.

This issue seems connected with #739 and #218 (that I've reported myself in the past), however, here we're talking about project's direct resources, and not resources of third-party libraries that are bundled. There is a chance that those issues are connected, as they also talk about resource files.

I'm not sure what else I can provide to help tackle down this issue, so please feel free to clone my **[repo](https://github.com/JustArchiNET/ArchiSteamFarm)**, switch to `mono-linker-crash-tests` branch and `dotnet publish ArchiSteamFarm -c Release -o out -r win-x64 -f netcoreapp3.0`. You can then change language of your OS to something like `pl-PL` or other `de-DE` and you should notice that strings are still in english, while non-trimmed output of `dotnet publish ArchiSteamFarm -c Release -o out -r win-x64 -f netcoreapp3.0 /p:PublishTrimmed=false` gives localized strings. Thank you.

**Comment by marek-safar** [comment] 2019-10-02 13:07
Duplicate of #739

**Closed by marek-safar** 2019-10-02 13:07 UTC
Labels: duplicate
