### ISSUE TITLE
Can't publish to Azure App Service : Error IL1012: IL Linker has encountered an unexpected error.

### ISSUE THREAD

**Issue by Tailslide** [mono/linker#1982] opened 2021-04-20 23:24 UTC
If I try to publish my webassembly blazor app to an azure app service I get this error. Complete output attached.

```
ILLink(0,0): Error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Matches(String input)
   at Mono.Linker.Steps.MarkStep.MarkTypeWithDebuggerDisplayAttribute(TypeDefinition type, CustomAttribute attribute)
   at Mono.Linker.Steps.MarkStep.MarkTypeSpecialCustomAttributes(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
   at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(41,5): Error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
```
[output.txt](https://github.com/mono/linker/files/6347121/output.txt)

**Comment by vitek-karas** [comment] 2021-04-21 12:21
This is a duplicate of https://github.com/mono/linker/issues/1648.
It has been fixed in .NET 6 in https://github.com/mono/linker/pull/1649. We didn't try to backport it.

@marek-safar do you think it would be worth backporting this to 5?

@Tailslide you can try to use .NET 6 Preview 3 which should have the fix? (You don't have to target .NET 6 with your app, just use .NET 6 SDK to build/publish the app).

**Comment by marek-safar** [comment] 2021-04-21 12:46
I think it's worth the backport. It's one line fix with no risk.

**Closed** 2021-04-21 12:46 UTC
Labels: duplicate

**Comment by Tailslide** [comment] 2021-04-21 15:53
@vitek-karas Thanks for your suggestions. I'm not sure what is involved with publishing with .NET 6, I'm just using the publish feature in VS2019 and I don't see an option for .NET 6.   I was able to work around this for now by adding this to my .pubxml:

``` 
<PublishTrimmed>False</PublishTrimmed>
```

Now I'm on to other problems. Publishing blazor webassemblies to azure AppServices is very painful so far.
