### ISSUE TITLE
Linker fails when adding a TrimmerRootAssembly

### ISSUE THREAD

**Issue by jeffschwMSFT** [mono/linker#853] opened 2019-12-10 20:44 UTC
Transfer of https://github.com/dotnet/runtime/issues/733#event-2872005294

When using PublishTrimmed=true for publishing single file applications in .net core, I get a runtime error when performing binary serialization/deserialization in System.Runtime.Serialization.Formatters library.

<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
The error during runtime received is:

System.TypeInitializationException: The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.Formatters.Binary.Converter..cctor()

   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.get_SystemAssemblyInfo()
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
I also tried adding the following to address this error:

<ItemGroup>
    <TrimmerRootAssembly Include="System.Runtime.Serialization.Formatters.Binary.Converter" />
</ItemGroup>
but that prevents it from publishing as it returns an error: C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(87,5): error MSB6006: "dotnet.exe" exited with code -1073741819.

I can disable PublishTrimmed=true for now, but I would think there's a way to address this.

The application is a .Net Core 3 app, which references two multi-target libraries which are netstandard2.0;net462

**Comment by PeterPann23** [comment] 2020-02-25 14:39
try and add the following to your csprj file
    <ItemGroup>
      <TrimmerRootAssembly Include="mscorlib" />
    </ItemGroup>

**Comment by sylvaingirardbe** [comment] 2020-04-15 12:28
Running into the same issue in a netcoreapp3.1 when publishing with
```
dotnet publish -c release -o /app -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true 
```

Setting `PublishTrimmed=false` fixes it. Resulting docker image is 15Mb bigger.

**Comment by aloksharma1** [comment] 2021-03-13 13:35
did this issue got solved? i'm having the same issue with blazor wasm publish, following is my blazor wasm project csproj file (its just a test using default template)
i am trying to use trim features of wasm assemblies but wants to keep some framework assemblies like runtime etc in the project for later uses, but its crashing on publish
here is the file input

<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

<PropertyGroup>
<TargetFramework>net5.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
<TrimmerRootAssembly Include="System.Security" />
</ItemGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
<WarningLevel>4</WarningLevel>
</PropertyGroup>

<ItemGroup>
<PackageReference Include="McMaster.NETCore.Plugins" Version="1.4.0-beta.41" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.4" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.4" PrivateAssets="all" />
<PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
</ItemGroup>

</Project>

what am i doing wrong here?
build succeeds but publish failes with error
ILLink(0,0): Error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'D:\Projects\Web\test\BlazorWasm\BlazorWasm\System.Security'.
File name: 'D:\Projects\Web\test\BlazorWasm\BlazorWasm\System.Security'

**Comment by marek-safar** [comment] 2021-03-15 14:55
@aloksharma1 your problem is a duplicate of #1772 which will be addressed in .NET6 P3. The original issue will be addressed as part of https://github.com/dotnet/runtime/issues/43078

**Closed by marek-safar** 2021-03-15 14:55 UTC
