### ISSUE TITLE
IL trimming: can we fall back to non-trimmed publishing on failure?

### ISSUE THREAD

**Issue by jaredpar** [mono/linker#1586] opened 2020-10-23 18:50 UTC
**Version Used**: 5.0.100-rc.2.20479.15

**Steps to Reproduce**:

1. Build a complex application
2. Try to publish it
3. Notice IL linker exception
4. Edit csproj to add  `<PublishTrimmed>false</PublishTrimmed>`
5. Never benefit from trimming again
6. Never actually remember that I had to set that flag
7. Wonder whether it couldn't just fall back to untrimmed publish when the linker crashes

**Expected Behavior**:

Well, ideally the IL trimming would work every time. I get that this is a really difficult thing and I'm okay with failures. Would it be possible to just perform a fallback to non-trimmed and display a giant warning? The end result the user wants from a `dotnet publish` is a published app. Ideally trimmed, yes, but that's sort of a nice-to-have on top, rather than a show-stopper. If there is such a failure, I either have to investigate (can take forever) or disable trimming (I guess that's the far more common action). What I actually would have wanted is a successful publish result, maybe with a warning that trimming didn't work.

**Actual Behavior**:

publish fails, and I have to add set `<PublishTrimmed>false</PublishTrimmed>`, which now permanently disables the benefit of trimmed publishing. I don't want to have to occasionally try whether it works now.

For reference, this is where it failed for me

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/home/runner/work/Blazor.Grids/Blazor.Grids/TestProject_ClientSide/TestProject_ClientSide.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasCustomAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.CustomAttributeSource.HasAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.HasLinkerAttribute[T](IMemberDefinition member)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Error: /home/runner/.dotnet/sdk/5.0.100-rc.2.20479.15/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/home/runner/work/Blazor.Grids/Blazor.Grids/TestProject_ClientSide/TestProject_ClientSide.csproj]
Error: Process completed with exit code 1.
```

**Comment by jaredpar** [comment] 2020-10-23 18:50
Manual move of Roslyn issue https://github.com/dotnet/roslyn/issues/48873

**Comment by tlakollo** [comment] 2020-10-23 19:43
IL1012 is one of the most important Linker errors that we have because it's an unknown fatal error. It helps the linker team to identify where we have holes both in the code and in our testing and therefore it's important that people report it. My fear is that if we fallback to publish only creating a warning it would disable trimming in a kind of silent way and will discourage people to report these issues.
Instead, someone reported this failure in #1496 and was fixed with #1535
Considering this is an opt-in feature and experimental I don't think is something we should pursue now. Maybe once trimming is on by default this should be a feature that we can work on.

**Comment by stefanloerwald** [comment] 2020-10-23 20:38
In blazor projects, this is not at all opt-in, that's why it's such a frustrating thing to encounter

**Comment by agocke** [comment] 2020-10-23 20:43
@stefanloerwald True, but I think crashes are simply unacceptable in the product. We should just fix the problem instead of hiding it. I'll work to make sure we're getting as much crash data as possible.

**Comment by stefanloerwald** [comment] 2020-10-23 20:45
A fix of course is always preferable over hiding. I'm glad that in this case, it seems that I simply have to wait for the next version. Looking forward to that!

**Comment by PathogenDavid** [comment] 2020-10-24 11:52
Personally I'd much rather have a failure rather than a silent retry-with-different-settings. (As the default, anyway.)

> publish fails, and I have to add set `<PublishTrimmed>false</PublishTrimmed>`, which now permanently disables the benefit of trimmed publishing. I don't want to have to occasionally try whether it works now.

@stefanloerwald You didn't specify how you're publishing your project, but if it's the command line you can temporarily override the setting with `-p:PublishTrimmed=false` instead of modifying your project file.

> 6\. Never actually remember that I had to set that flag

If you aren't publishing from the command line and you still want to make sure this doesn't happen without relying on something external like an issue tracker, you can add your own warning:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  
  <Target Name="TrimmingDisabledWarning" Condition="'$(PublishTrimmed)' != 'true'" AfterTargets="Publish">
    <Warning Text="****************************************************************************
PublishTrimmed is disabled due to https://github.com/mono/linker/issues/1586
Make sure to re-enable it once the issue is resolved.
****************************************************************************" />
  </Target>

</Project>
```

**Comment by marek-safar** [comment] 2020-10-26 09:05
This is a bug in the tool which fits into a category which we'll always want to fix. In this case, this is actually duplicate of #1496 as was mentioned earlier.

**Closed by marek-safar** 2020-10-26 09:05 UTC
Labels: duplicate
