### ISSUE TITLE
Consider exposing trimmed types in an assembly

### ISSUE THREAD

**Issue by LakshanF** [mono/linker#1804] opened 2021-02-05 00:18 UTC
An incorrectly trimmed application can fail in unexpected ways that will be very hard to diagnose in a production environment. It will help the developer experience if there is a way to provide diagnostic information about trimmed part of the application during testing. Marking trimmed assemblies, [Consider marking linked assemblies on the output](https://github.com/mono/linker/issues/1194), is a good start and extending the idea to type level would be a good next step. 

Having this would help components that leverage problematic coding patterns like reflection which can cause problems for the linker to reason about dependency closure. For examples, some serializers rely on reflection to get properties of objects and the linker can remove the getters of these types. Another problematic area is the polymorphic “type discovery” problem – the inability of the trimmer to reason about runtime type – and the potential to trim away types in an object inheritance hierarchy. Marking trimmed types in an assembly would allow runtime discovery of types available and allow applications that rely on problematic reflection code to discover affected types during testing. For example, serializers can provide a diagnostic mode to let developers discover usage of trimmed types that could cause problems in their application in deployed mode. 

The biggest concern with this proposal would be the additional size impact on the trimmed assembly. One approach that seems promising would be to store tokens of the trimmed types and expose a method that returns a flag if a type is trimmed. The method can check via loading the token to determine if the type is trimmed or not. The storage of the trimmed type tokens for an assembly can be optimized via a bitmap to point to the typedef tokens in the assembly (1=trimmed).

**Comment by MichalStrehovsky** [comment] 2021-02-05 08:44
Storing tokens or bitmaps of tokens is problematic because there might be tools (e.g. [Fody](https://github.com/Fody/Fody)) that run after trimming, shaking up the tokens and not knowing there's a data structure that needs to be fixed up. This leads to sadness. One approach we've used in .NET Native (that is somewhat cheaper than emitting entire custom attributes, which would be the next best way to encode this) was to generate a method that has a series of LDTOKEN of the interesting tokens. This implies 5 bytes per type. Method bodies can be accessed at runtime through reflection.

I'm wondering whether trimmed/not trimmed would be sufficient granularity. For example a serializer doesn't really care if we trim non-property methods when it's looking for properties. If we only have 1 bit of information, the only way for this diagnostic not to kick in would be to keep the type in entirety. I'm wondering whether storing more bits would lead to savings in the end - e.g. we can remove non-property methods, and set a bit that methods were stripped but properties were kept intact. `GetProperties` API would be completely safe, `GetMethods` would be problematic.

If we do go the LDTOKEN route, my suggestion would be to add a public API in CoreLib to access this information so that publishing modes that can strip method bodies (both Mono AOT and NativeAOT does this) can do so for this method. It would be possible to transform this to a more efficient representation by the AOT pipeline that doesn't play by the ECMA format rules anymore. But that requires the API that reads this information to version with the underlying runtime.

**Comment by marek-safar** [comment] 2021-02-05 14:06
Can you provide an example of how this information would be used in practice? I'm a bit concern that this can be also quite misleading unless we define trimming very strictly. For example, would method body rewrite be considered as trimming or empty static constructor removal? Secondly, where would you encode the information about completely removed types, module constructors, or assembly attributes?

**Comment by LakshanF** [comment] 2021-02-05 16:34
This capability can be leveraged during runtime by components that uses reflection to discover potential problems. An example would be of a serializer having a diagnostic mode that warns an application developer of problematic types during an object graph’s transitive closure computing time. 

The trimming definition is an important point. We can start with the similar definition @vitek-karas has for the assembly [attribute](https://github.com/mono/linker/issues/1194#issuecomment-731410319), “the content of the type has been modified and it's not guaranteed that it is equivalent to the type on input". We also have the option to enhance this along the @MichalStrehovsky's suggestion above.

This proposal does not cover a mechanism to track completely removed types. Runtime usage similar to serializer example should be able to detect removed types independent of this mechanism.

**Comment by marek-safar** [comment] 2021-02-05 16:54
> An example would be of a serializer having a diagnostic mode that warns an application developer of problematic types during an object graph’s transitive closure computing time.

Would this check be aggressive (e.g. check every type before something goes wrong)?

> "the content of the type has been modified and it's not guaranteed that it is equivalent to the type on input"

By default, we are going to trim core libraries at most (no user assemblies trimming). Do you expect there will be any type in the core libraries that won't be touched by linker during trimming? For example, the linker removes all nullable annotations.

**Comment by vitek-karas** [comment] 2021-02-08 14:14
### Storage

Another option for "storage" would be to emit a method which answers the question `_IsTypeTrimmed(Type)` for types from the assembly where it's defined - the body would be something like a switch using `ldtoken` to refer to the known trimmed types. This should work well with any IL post-processing tool (unless it does its own trimming, but that's out of scope for this).

I do agree that we should expose an API (in CoreLib) which will be the simple check, internally it could then find the type's assembly, and look for the generated `_IsTypeTrimmed` method and call it to get the answer. The consumer would not know about this implementation detail.

### Semantics

Whatever the semantics will be, it needs to map to some action the user can take to "fix" it. So for example if a serializer reports to the user that type `MyEmail` has been trimmed (and thus might not serialize correctly), there should be a relatively simple action for the user to fix this.

Because of this, I was thinking we would define the semantics the same way to what descriptors do. So fixing the above should be achievable by adding `MyEmail` to the descriptor XML for the app. Internally this effectively translates to `MarkEntireType`, which would also nicely work with `DynamicallyAccessedMemberType.All` which does the same thing. Also `DynamicDependency` can do this.

So one proposal could be that all types which went through `MarkEntireType` are considered "not-trimmed" for the purposes of this API. The rest of the logic is simple: If the type is in an assembly which was not trimmed -> it's not trimmed. If the type is in an assembly which is trimmed, by default it's assumed to be trimmed, unless it's listed specifically as "not-trimmed".

### Impact on default Xamarin/Balzor modes (SDK-only trimming)

For the default SDK-only trimming mode, the impact of this should be really small - probably a handful of types in the framework (we need to measure this).

This doesn't mean that the type is completely untouched (mainly because we don't have a user action to make type completely untouched), so for example attribute removal could still occur. Attributes are somewhat different problem - if a component needs a certain attribute, then it needs to explicitly preserve it (via `DynamicDependency` for example) - there's a warning for this and we need to annotate framework assemblies correctly (so far I'm not aware of any case of this in the core framework).

**Comment by MichalStrehovsky** [comment] 2021-02-08 15:20
I think if we're considering emitting an actual callable method that decides whether a given type was trimmed, it might be cheaper to just put a custom attribute on the type. Applying a custom attribute on a type "costs" around 12 bytes of metadata. LDTOKEN by itself is 5 bytes of IL and we haven't done anything with it yet, just pushed it on stack - do something with it and the 7 bytes of advantage run out quick.

> So for example if a serializer reports to the user that type MyEmail has been trimmed (and thus might not serialize correctly), there should be a relatively simple action for the user to fix this.

The fix could be to just suggest to preserve the type in entirety, but I think it would be advantageous if these "asserts" didn't trigger more often than necessary. E.g. if we're considering understanding `[DataContract]` and `[DataMember]` to preserve properties and the user _did_ annotate their type with these, it would be annoying if the serializer still complained if we strip e.g. a static method off the type and required the user to also root all members on the type just to shut up the "assert". Having a way to get to the granularity of the trimming would be useful for that. It's not a panacea, but I think it would work pretty often.

**Comment by vitek-karas** [comment] 2021-02-08 15:31
I honestly don't think size is the main concern here - I don't expect 1000s of types to be marked like this.
With one exception - Blazor's "type-level" trimming - in that case attributes would not work (every type would have it), but the method would be trivial (just return true for everything). It gives better flexibility in that regard.

Encoding it with just `ldtoken; pop` like we did in .NET Native - I don't know if I like "parsing" method body in some CoreLib function - that feels really weird. For example, such method would not work in AOT, but if the method directly returned the desired value it would be compilable with AOT just like any other method.

I thought about the specific serializer steps - currently it's a moot point, since none of them actually implement the correct/full behavior of the serializer. But if it did, it could emit a similar method into the affected assembly, and then the serializer would need to look for that method. I don't think in such case it should go into a "common" method (or attribute) - I personally would prefer a private contract between the custom step and the serializer.

**Comment by MichalStrehovsky** [comment] 2021-02-08 20:28
The extra method would probably also be pretty expensive to ready to run compile (each LDTOKEN is basically a call with fixups and stuff) and if we mark it as ready-to-run-ignore, it might take pretty long to JIT if it's several kilobytes long, which it might often be.

**Comment by vitek-karas** [comment] 2021-06-16 15:24
There are no plans to add this right now, so closing this.

**Closed by vitek-karas** 2021-06-16 15:24 UTC
Labels: proposal

**Comment by jzabroski** [comment] 2022-08-17 20:58
I had mentioned on Twitter 2 or 3 years ago what I thought was the reasonable compromise here:

Emit a `tombstone.jso`n file that emits the trimmed types, so that exceptions caused by not finding a concrete type (e.g., when resolving a type through Microsoft.Extensions.DependencyInjection) have a clear explanation of whether it was caused by trimming, or some other reason.

So, I don't think it needs to be in the assembly metadata, but having it somewhere would probably be smart.

**Comment by vitek-karas** [comment] 2022-08-22 16:46
> Trimming is altogether a rather silly thing to me, when you consider what .NET would look like with higher-kinded type constructors.

I must admit I don't understand this. The simple trimming is no different from what platform linker does for native code (it also removes code which is not referenced anywhere in the binary), unfortunately for .NET it gets really complicated due to reflection.
