### ISSUE TITLE
Different Queue Type Used After Publish in Formatter

### ISSUE THREAD

**Issue by steveisok** [mono/linker#1594] opened 2020-10-27 13:09 UTC
Given a simple console app csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```

After publish, you'll notice that the assembly ref for the Queue class used in the constructor for `System.Runtime.Serialization.Formatter` has changed.  It goes from `System.Collections.NonGeneric` to `System.Collections.Concurrent`.

Before:
```
IL_0007: newobj instance void [System.Collections.NonGeneric]System.Collections.Queue::.ctor()
IL_000c: stfld class [System.Collections.NonGeneric]System.Collections.Queue System.Runtime.Serialization.Formatter::m_objectQueue
```

After:
```
IL_0007: newobj instance void [System.Collections.Concurrent]System.Collections.Queue::.ctor()
IL_000c: stfld class [System.Collections.Concurrent]System.Collections.Queue System.Runtime.Serialization.Formatter::m_objectQueue
```

**Comment by vitek-karas** [comment] 2020-11-01 23:16
The produced code is broken, the `Queue` type doesn't exist in `System.Collections.Concurrent` (not even as a type forwarder). Building an app which overrides `Formatter` and news it up ->
```console
Unhandled exception. System.TypeLoadException: Could not load type 'System.Collections.Queue' from assembly 'System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Runtime.Serialization.Formatter..ctor()
   at queue.TFormatter..ctor() in F:\ILLinker\repro\queue\Program.cs:line 20
   at queue.Program.Main(String[] args) in F:\ILLinker\repro\queue\Program.cs:line 13
```

**Comment by marek-safar** [comment] 2020-11-02 09:34
@vitek-karas @agocke could you assign someone on this, this looks quite bad

**Comment by vitek-karas** [comment] 2020-11-02 09:36
@tlakollo could you please take a look and try to determine at least roughly where the problem is?
I do agree it looks bad, on the other hand, this must be something rather rare, otherwise linker would be breaking apps left and right.

**Comment by MichalStrehovsky** [comment] 2020-11-02 09:53
@mateoatr has already been looking into it (he was asking me for pointers), so maybe sync up with him first.

**Comment by vitek-karas** [comment] 2020-11-02 09:54
Thanks - reassigned to @mateoatr

**Comment by mateoatr** [comment] 2020-11-03 17:42
`System.Collections.NonGeneric` is never marked, which makes the linker annotate it with `Delete` in the sweep step and then remove it from all the assemblies which have a reference to it (such as `System.Runtime.Serialization.Formatters`, SRSF). When we enter the output step and [write out SRSF](https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/OutputStep.cs#L127), Cecil recalculates all the assembly references and [assigns them a new md token](https://github.com/mono/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L1144), giving `System.Collections.Concurrent` a RID equal to 2 (the same RID that SCNG had before removing it from the assembly refs of SRSF).
Later on, when Cecil writes out the method body of `Formatter::.ctor`, we have everything in place: Cecil knows that the scope of `Queue` corresponds to SCNG, but the md token of SCNG is now the one of SCC (`AssemblyRef:0x0002`), causing trouble when [creating the type ref row](https://github.com/mono/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L1378) for `System.Collections.Queue`.

**Comment by vitek-karas** [comment] 2020-11-03 18:28
So if I understand it correctly there are two issues here:
* linker should mark System.Collections.NonGeneric because one of the kept assemblies has code in it which has a direct reference to it. Where you able to track down how come we don't mark the assembly? Do we even mark the `Queue` type?
* Cecil effectively corrupts the output if it has unresolved references. While interesting from pure Cecil's point of view, it doesn't seem to be that important to linker - in this case linker screwed up. Even if Cecil can write the code correctly, it would still contain a reference to non-existing assembly.

Given that this happens in the default "assembly-level" trimming mode, it is sort of weird:
* It's OK for linker to write out code which will have unresolved assembly refs in it - but only if linker thinks such code is not reachable
* As such even if the unreachable code is corrupt on output, it should not matter for the app itself (runtime should be lazy enough to avoid even looking at the code).

Eventually I think we should fix both issues - the corrupted code on the output can break tooling (or even runtime) eventually, so it's a bad thing, but it's not a pressing issue right now (I think).

**Comment by mateoatr** [comment] 2020-11-03 19:10
> Do we even mark the Queue type?

No. The only things that get marked in System.Runtime.Serialization.Formatters are under Binary.BinaryFormatter, which are marked because of [this](https://github.com/dotnet/runtime/blob/b5705587347d29d79cec830dc22b389e1ad9a9e0/src/libraries/System.Private.CoreLib/src/System/Resources/ResourceReader.Core.cs#L78-L83). Neither `Queue` nor anything in System.Collections.NonGeneric gets marked - binary formatters do not use anything there. `Formatter::.ctor` is not reachable, if I use `link` instead of `copyused` for the assembly, it'll be removed.

**Comment by vitek-karas** [comment] 2020-11-03 20:19
The Cecil issue seems to be more serious than I thought. If I write code which takes a hard dependency on `Formatter..ctor` linker will actually mark `Queue` and it will keep `System.Collections.NonGeneric.dll` in the output (the assembly is marked with action `Save`), but the `Formatter..ctor` still has a type ref to `Queue, System.Collections.Concurrent` which doesn't exist.

The fact that we don't mark `Queue` in the default hello world is as expected and that is fine. The expectation is for the linker to keep `Formatter..ctor` and keep it pointing at `Queue, System.Collections.NonGeneric`. The code should not be reachable at runtime, and thus the missing assembly reference should not matter.

**Comment by vitek-karas** [comment] 2020-11-03 20:21
I'm using a repro which is a template console app with code like this: https://gist.github.com/vitek-karas/bd538cd5d35506b255d8031f2b929e95

**Comment by vitek-karas** [comment] 2020-11-11 14:44
Super weird. I installed .NET 5 RTM SDK today and rerun the repro... and it works just fine.
So we probably took an updated Cecil version somewhere along the way?

Can somebody else please verify that this works as expected on 5 RTM?

**Comment by mateoatr** [comment] 2020-11-11 19:50
> Can somebody else please verify that this works as expected on 5 RTM?

I can also verify that your repro app works just fine (the hello world app still has `System.Collections.Concurrent` on `m_objectQueue` though.)

**Comment by marek-safar** [comment] 2020-12-10 18:31
@steveisok is this issue still reproducible with newer SDK?

**Closed** 2021-03-01 09:42 UTC
Labels: area-Linker: Steps, needs more info
