### ISSUE TITLE
Blazor's linking throws BadImageFormatException on projecs referencing Peachpie.App

### ISSUE THREAD

**Issue by petrroll** [mono/linker#488] opened 2019-03-18 22:28 UTC
Most recent version of blazor (`0.9.0-preview3-19154-02`) fails on linking phase with `BadImageFormatException` when the project references `Peachpie.App`.

Repro:
1. Follow blazor [Getting started](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli)
2. Edit `WebApplication1.csproj`: Add `<PackageReference Include="Peachpie.App" Version="0.9.36"/>`
3. Run dotnet build.

Expected: build works fine.
Actual: Fails:

Full output of dotnet build: [here](https://gist.github.com/petrroll/6b3d8d59a7a6c15128ae735176ef3855)
Exception in question:
```
  WebApplication1 -> C:\Users\housk\Source\blazor-exp\WebApplication1\bin\Debug\netstandard2.0\WebApplication1.dll
  Fatal error in IL Linker
  System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
     at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics, UInt16& linker)
     at Mono.Cecil.PE.ImageReader.ReadImage()
     at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
     at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
     at Mono.Linker.LinkContext.Resolve(String name)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

The exception seems to be originating [here](https://github.com/jbevain/cecil/blob/master/Mono.Cecil.PE/ImageReader.cs#L196).

The `Peachpie.App` package shouldn't contain any Peachpie compiled resources (should be 100 % C# code) so it's unlikely Peachpie's bug.

**Comment by marek-safar** [comment] 2019-03-21 11:12
Could you upload content of `C:\Users\housk\Source\blazor-exp\WebApplication1\bin\Debug\netstandard2.0` ?

**Comment by petrroll** [comment] 2019-03-24 08:33
Complete project: https://1drv.ms/f/s!Ak2iL3P_ifT3hd88EmB8T0NCCPw6MA

For now ignore the subfolder called PHPLib. The state of the files is after following steps:

1. Created Blazor template app.
2. Successfully `dotnet build` the clean Blazor template app.
3. Referenced `Peachpie.App` runtime libraries.
4. `dotnet build` failed.  

My usecase: I was trying to make Blazor work with [Peachpie](https://github.com/peachpiecompiler/peachpie
) compiled assemblies (and the PhpLib folder contains a very simple PhpLibrary) but it seems that the Linker fails even if the peachpie compiled `.dll` isn't referenced at all (Line: 17-19@`\WebApplication1.WebApplication1.csproj`) and only our runtime libraries (that are written in pure C#, compiled by Roslyn) are (Line 21@`\WebApplication1.WebApplication1.csproj`).

**Comment by acorrow** [comment] 2019-03-24 18:24
I get the same exact error, only I create a new Blazor template app, then added some references to System.Data and System.Data.SqlClient, added some quick Code to hit my SQL Instance, and now get this error. Built fine prior. Verbatim same exact stack. Same preview build.

**Comment by petrroll** [comment] 2019-03-24 18:53
I'm pretty sure `System.Data.SqlClient` and/or `System.Data` are somewhere in the dependency chain of `Peachpie.App` as well.

**Comment by acorrow** [comment] 2019-03-24 21:26
Verified Steps to reproduce:

1: Create project with Blazor template as listed above
2: Import nuget (Whole Project): System.Data.Common and System.Data.SqlClient
3: Build: ERROR

**Comment by acorrow** [comment] 2019-03-25 00:15
Removing the reference to System.Data.SqlClient fixes the issue.

**Comment by acorrow** [comment] 2019-03-25 00:19
Doe NOT happen if you only include the Reference to System.Data.SqlClient in the SERVER project, not the CLIENT or SHARED projects....

**Comment by acorrow** [comment] 2019-03-25 15:59
Adding any Lib that references System.Data.SqlClient on any project OTHER than the SERVER project throws this error. Sorry for the redundant comments here, but that is the root. I've tried a number of versions/combinations. And that is the key. System.Data.SqlClient can be added to the SERVER, no where else.

**Comment by petrroll** [comment] 2019-03-29 22:31
Confirming that the issue lies solely in `System.Data.SqlClient`. Blazor runs with peachpie perfectly fine without it.

**Comment by bfistein** [comment] 2019-09-25 20:35
@marek-safar any idea if this perhaps may have already been addressed in .NET Core 3.0?

**Comment by marek-safar** [comment] 2019-10-02 13:42
I tried but I still cannot reproduce it locally. Sharing the content of the folder or some self-contained project is probably best

**Comment by bfistein** [comment] 2019-11-09 14:58
@petrroll could you maybe provide the project (ideally w/o PeachPie itself) to @marek-safar?

**Comment by petrroll** [comment] 2019-11-09 15:04
I'll check, it might actually be fixed.

**Comment by petrroll** [comment] 2019-11-09 17:19
Failing with reference peachpie: https://1drv.ms/u/s!Ak2iL3P_ifT3hflPxOJHK4-GmA6P7Q?e=dkb3Cc

```
PS C:\Users\...\WebApplication2> dotnet --version
3.1.100-preview2-014569
PS C:\Users\...\WebApplication2>
```

**Comment by bfistein** [comment] 2019-11-09 17:29
Thanks @petrroll !

**Comment by bfistein** [comment] 2020-09-16 08:54
Quick bump, @marek-safar, did you manage to reproduce the issue locally?

**Comment by TomatorCZ** [comment] 2020-10-04 19:50
It works fine with Peachpie and Blazor template for me.

Project info:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Peachpie.App" Version="1.0.0-preview2"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0-preview3.20168.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0-preview3.20168.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
  </ItemGroup>
</Project>`

**Comment by marek-safar** [comment] 2020-10-06 12:24
@bfistein no, does it still fails for you with 5.0 version?

**Comment by bfistein** [comment] 2020-10-06 12:26
Afaik it seems to work, feel free to close this for now.

**Closed** 2020-10-06 13:05 UTC
Labels: needs more info
