### ISSUE TITLE
Supporting both RequiresUnreferencedCode and DynamicallyAccessedMembers annotations on a method

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1815] opened 2021-02-09 01:19 UTC
In https://github.com/dotnet/runtime/pull/47938, we are annotating a method with both `RequiresUnreferencedCode` and `DynamicallyAccessedMembers` attributes. This should do both:

* Raise an ILLink warning when someone calls it
* Preserve the necessary members that are dynamically accessed.

See https://github.com/dotnet/runtime/pull/47938#discussion_r571437223.

The scenario here is that part of a method may be trim compatible (like using Reflection to find a method by name), but another part may be incompatible (like calling `MakeGenericMethod` if the caller passed in a `Type[] typeArguments` value).

We should ensure this scenario works as expected.

**Comment by vitek-karas** [comment] 2021-02-11 22:31
The intended behavior is:
* Callers will get a warning due to the RequiresUnreferencedCode
* Callers will apply the requirements of the DynamicallyAccessedMembers on the method parameters
* The method body will not produce data flow warnings
* The method body is still fully analyzed and if it adds requirements on something that will be applied

#1827 adds a test to validate this - but it already works that way.

**Comment by vitek-karas** [comment] 2021-02-12 20:31
As noted above, the behavior is already as expected and the test coverage has been merged.

**Closed by vitek-karas** 2021-02-12 20:31 UTC
Labels: area-Linker: Diagnostic
