### ISSUE TITLE
Mono.Cecil.ResolutionException: Failed to resolve System.Void Microsoft.Net.Http.Headers.EntityTagHeaderValue::.ctor(System.String)

### ISSUE THREAD

**Issue by jasontseu1983** [mono/linker#152] opened 2017-08-30 03:28 UTC
Try to compile the AspNetCore 2.0 project with IL Linker nuget

dotnet publish -c release -r linux-x64 -o out /p:ShowLinkerSizeComparison=true

Fatal error in IL Linker
Mono.Linker.MarkException: Error processing method: 'System.Boolean Microsoft.AspNetCore.StaticFiles.StaticFileContext::LookupFileInfo()' in assembly: 'Microsoft.AspNetCore.StaticFiles.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Microsoft.Net.Http.Headers.EntityTagHeaderValue::.ctor(System.String)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run()
   at Mono.Linker.Driver.Main(String[] args)

**Comment by sbomer** [comment] 2017-09-21 17:26
Just noticed that this was assigned to me. I'm not able to reproduce this with a simple asp.net core app (created using `dotnet new web`), and the latest version of the linker (`dotnet add package ILLink.Tasks -v 0.1.4-preview-981901`). @jasontseu1983, are you able to provide more detailed repro information?

**Comment by marek-safar** [comment] 2018-01-22 16:37
Closing as no more details were provided

**Closed by marek-safar** 2018-01-22 16:37 UTC
Labels: needs more info
