### ISSUE TITLE
ILLink : error IL1012:

### ISSUE THREAD

**Issue by xljiulang** [mono/linker#1583] opened 2020-10-23 04:57 UTC
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [D:\taichuan\5kcore\src\ReaderApp\ReaderApp.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasCustomAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.CustomAttributeSource.HasAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.HasLinkerAttribute[T](IMemberDefinition member)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)

**Comment by marek-safar** [comment] 2020-10-23 08:13
Could you please provide .NET version details?

**Comment by xljiulang** [comment] 2020-10-23 08:55
5.0.100-rc.2.20479.15

**Comment by vitek-karas** [comment] 2020-10-23 09:45
This is likely fixed by https://github.com/mono/linker/pull/1535. Could you please try the latest RTM build?
https://github.com/dotnet/installer (in the table from the 5.0.100 RTM column).
Please note that you will likely need the workaround mentioned in https://github.com/dotnet/installer/issues/8882#issuecomment-713229300 to get it work properly.

**Comment by xljiulang** [comment] 2020-10-26 01:20
@vitek-karas 
```
dotnet publish -c Release -v m -o .\app -r win-x86 /p:version=2020.10.26.0916 /p:PublishTrimmed=true /p:BinType=WinExe
```
```
Microsoft (R) Build Engine version 16.8.0-preview-20475-05+aed5e7ed0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

 Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasCustomAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.CustomAttributeSource.HasAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.HasLinkerAttribute[T](IMemberDefinition member)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
```

```
C:\Users\laojiu>dotnet --version
5.0.100-rtm.20515.8
```

**Comment by vitek-karas** [comment] 2020-11-03 20:04
That looks like it could be fixed with https://github.com/mono/linker/pull/1535
We haven't ported that to 5.0 though.

This would only happen if your application has an attribute in it which is from an assembly which is not part of the app. Do you know if you application is missing some dependencies?

**Comment by xljiulang** [comment] 2020-11-04 00:31
Some dll were referenced in my project.
```
 <Reference Include="xx">
      <HintPath>Libs\xx.dll</HintPath>
    </Reference>
```

**Comment by vitek-karas** [comment] 2020-11-04 13:35
That alone should not be a problem, unless the file it hints to doesn't exist (but I would expect the build to fail then much earlier). This is likely from a .dll which you don't build (you consume it as either NuGet or as plain `.dll`) and it has a dependency which the app doesn't contain. 

One way to find out (it's not ideal) would be:
* build the app with `-bl` on the command line (let it fail with that)
* this will produce `msbuild.binlog` file which you can open with https://msbuildlog.com/
* Search for `$task ILLink` and then copy the value of the CommandLine from that task
* Run the command line from console - this should fail the exact same way as running the build
* The command will end with `--skip-unresolved true`, remove that and run it again - I would hope it now reports the missing dependency

**Comment by marek-safar** [comment] 2020-11-13 15:13
I think we should backport the fix, it's pretty small

**Comment by marek-safar** [comment] 2020-11-20 12:17
Closing as duplicate of #1496

**Comment by vitek-karas** [comment] 2020-11-20 12:22
#1496 is not the same problem. The code which is problematic in this case is (just a sample, not the actual code from the app since that doesn't matter):

```C#
Lazy<System.Web.Extensions.JsonHelper> _myField;
```

`System.Web.Extensions` doesn't exist, so it's Lazy<unresolved type>. But there's `Lazy<[DynamicallyAccessedMembers(ParameterelessConstructor)] T>` - so data flow kicks in and tries to figure out what the T is. But that fails. Currently we don't handle this correctly and fail with the above error.

**Comment by marek-safar** [comment] 2020-11-20 12:26
@vitek-karas are you sure? I don't see any data flow here, the call stack is from `MarkStep.MarkEntireTypeInternal`.

**Comment by vitek-karas** [comment] 2020-11-20 13:14
I'm sorry - you're right - I confused this issue with #1634. The title is nearly identical - I'll change them.

**Closed by vitek-karas** 2020-11-20 13:14 UTC
Labels: area-Linker: Steps, regression
