### ISSUE TITLE
Mono Wasm CI failure when bumping to PR #502

### ISSUE THREAD

**Issue by alexanderkyte** [mono/linker#541] opened 2019-04-18 22:31 UTC
There is a bisect trail at https://github.com/mono/mono/pull/14126 that shows that the linker PR https://github.com/mono/linker/pull/502
is shown to cause a number of tests in the aot-mini harness to flake.

This failure is preventing this bump:

https://github.com/mono/mono/pull/14104

**Comment by alexanderkyte** [comment] 2019-04-19 16:53
@mrvoorhe how would you like to handle the regression? I can do the github-foo to get any linker changes you make tested on our CI before merge, if that will help you any.

If you build https://github.com/mono/mono/pull/14126/commits/d793f52b75a46fcb3db79ae693fc991ce3c2af98 from https://github.com/mono/mono/pull/14126 you should see the failures that we see on CI here: https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/11939/

**Comment by mrvoorhe** [comment] 2019-04-19 17:23
Can you clarify exactly what failures you are referring to?  There is a lot of text in that build log and I'd like to be sure we are looking at the same thing.

First I'd like to check and see if this is a regression in the linker or more of an API break and mono class libraries need to be updated.  I've made a number of PR's recently that have built on optimizations that can be made when no instance of a type is ever created.

Any type that
* Has an instance created on the native side...and
* No managed code code path is marked which calls a .ctor for that type

Will be incorrectly labeled as "never instantiated" by the linker.  With each successive optimization the risk is greater that a type that is not properly annotated will have an optimization applied to it that results in a problem.  If this is what is happening, then the fix will be on the mono side.

**Comment by mrvoorhe** [comment] 2019-04-19 17:30
FYI, the optimization introduced in https://github.com/mono/linker/pull/502 has a command line flag that will let you disable it.  If you want to proceed with your linker revision bump in mono while we sort this out you could temporarily disable this new optimization over in mono.

**Comment by alexanderkyte** [comment] 2019-04-19 20:25
We aren't really getting much debug output here when it fails, it just reports a failure. It seems like it's trying to run `test_0_enum_comparer` when it fails. I would wager that the body has been stripped there. 

If you look at https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/11939/
there is one failing suite, aot-mini. The failure seen is 

```
WASM: Running 'test_0_arm64_gsharedvt_out_vtypebyref' ...
WASM: Running 'test_0_arm64_dyncall_vtypebyref_ret' ...
WASM: Running 'test_42_arm64_dyncall_vtypebyval' ...
WASM: Running 'test_0_arm64_ios_dyncall_vtypeonstack_align' ...
WASM: Running 'test_0_arm_dyncall_reg_stack_split' ...
WASM: Running 'test_0_partial_sharing_regress_30204' ...
WASM: Running 'test_0_dyncall_nullable' ...
WASM: Running 'test_0_arm64_dyncall_vtypebyrefonstack' ...
WASM: Running 'test_0_enum_eq_comparer' ...
WASM: Running 'test_0_enum_comparer' ...
WASM: ABORT: 26144856
undefined
REGRESSION TEST FAILED
WASM-ERR: exit(1) called, but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)
Makefile:218: recipe for target 'run-aot-mini' failed
make: *** [run-aot-mini] Error 1
```

I'll add that command line flag to mono for the bump though, thanks

**Comment by mrvoorhe** [comment] 2019-04-24 20:35
I'm pulling the unreachable bodies change into unitylinker & il2cpp so I thought I would take a look at what happens for us if I add the same test you have.

I added a test to our suite that looks like
```
        [Test]
        public void TestEnumComparer ()
        {
            var c = Comparer<MyEnum>.Default;
            Trace(c.Compare (MyEnum.One, MyEnum.Two));
            Trace(c.Compare (MyEnum.One, MyEnum.One));
            Trace(c.Compare (MyEnum.Three, MyEnum.Three));
            Trace(c.Compare (MyEnum.Three, MyEnum.Four));
        }
```

That should be relatively similar to your `test_0_enum_comparer`.  Admittedly even though our test is functionally equivalent, what I was testing may not be apples to apples since our other tests may cause a difference in what is stripped from the class libraries.  So while the above test passed for us, that doesn't mean it's a fair comparison.

I'm assuming the problem you hit happens during the call to `System.Collections.Generic.Comparer`1.Default`.  Is this the comparer.cs you are using https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/collections/generic/comparer.cs ?  If so, in `CreateComparer` are you compiling with or without `MONO` set?

**Comment by alexanderkyte** [comment] 2019-04-25 20:54
A quick experiment confirmed that we compile that file with MONO set.

**Comment by mrvoorhe** [comment] 2019-04-26 13:10
Thanks.  So do we.  So the code path my test took should have been roughly the same as yours.  Maybe it would be worthwhile to try adding a linker test that does the same thing and have core libraries set to link. 
 Then try to run the output assembly.  I can give it a try next week.

**Comment by marek-safar** [comment] 2019-10-03 08:21
Duplicate of #612

**Closed by marek-safar** 2019-10-03 08:21 UTC
Labels: duplicate
