### ISSUE TITLE
Linker error "member is declared in another module and needs to be imported" after PR #502

### ISSUE THREAD

**Issue by akoeplinger** [mono/linker#612] opened 2019-06-09 18:35 UTC
We're seeing this issue in the Xamarin.iOS integration of the latest linker sources: the linker throws an exception like `Member 'System.Boolean _unregistered' is declared in another module and needs to be imported`.

I tracked it down to #502, which also seems to have caused other issues like https://github.com/mono/linker/issues/541.

Unfortunately I don't have time to investigate this right now and talking with @mrvoorhe on Slack he doesn't either so we agreed it's best to disable this new feature by default for now.

**Comment by marek-safar** [comment] 2021-02-26 17:53
I tried to reproduce it but could not. We have also re-enabled the optimization and everything seems to be fine now so closing.

**Closed by marek-safar** 2021-02-26 17:53 UTC
Labels: area-Linker: Steps, regression
