### ISSUE TITLE
Avoid trimming COM interfaces in library mode

### ISSUE THREAD

**Issue by agocke** [mono/linker#2881] opened 2022-07-05 17:50 UTC
When trimming in library mode we don't know if built-in COM will be disabled or enabled. If it's enabled, then nothing on the interface can be trimmed, similar to `StructLayoutKind.Explicit`. There are currently no situations in which BuiltInCom is enabled and trimming is enabled in app-mode, but that still shouldn't affect behavior in library mode, where we don't know.

**Comment by agocke** [comment] 2022-07-05 17:51
fyi @AaronRobinsonMSFT @jkoritzinsky

**Comment by agocke** [comment] 2022-07-05 17:52
@LakshanF Could you take a look at this after you finish fixing up the NativeAOT package to allow overriding the SDK version?

**Comment by AaronRobinsonMSFT** [comment] 2022-07-05 22:10
/cc @dotnet/interop-contrib

FYI @roji this would result in an explicit run-time error as opposed to the "it seems to sort of work" scenario for COM we were experiencing.

**Comment by MichalStrehovsky** [comment] 2022-07-06 00:43
"COM interface" is a very loose term because all interfaces are COM interfaces unless the assembly specifically says `[ComVisible(false)]` (and nobody does that). I assume we want to do this when the interface is marked `[ComImport]` which would kick in this specific case. I.e. it would not kick in for the `IResourceManagerShim` or `IDtcProxyShimFactory` interface in @roji's branch because those are not marked as ComImport, but still used with COM. Would this move the needle enough to be useful?

> /cc: @kant2002

Just to avoid confusion, this is only for running il linker in library mode. It's a special mode that is unsupported outside dotnet/runtime repo - it's used to trim unused code in shared framework. We do not intend to do anything to support built-in COM for end user scenarios (`PublishTrimmed=true`). We would still not preserve anything on ComImports in user code. Built-in COM needs to be turned off for trimming to be reliable due to the issues like the one I just pointed out above.

**Comment by MichalStrehovsky** [comment] 2022-07-06 01:53
> If it causes a type load failure or any run-time failure other than dispatch that just works, yes

So basically the request is to keep all interface methods on all types (not just the ones marked ComImport) unless we see `ComVisible(false)` on the assembly or interface type. Just to repeat - even in @roji's branch, there are interfaces used with COM that not marked as ComImport. We haven't seen horrible failure modes on dispatch just because we happen to use all the methods on the interface, but that's just luck. The only way to prevent that failure mode is not to trim interfaces.

I wonder whether instead of making the framework bigger, we should instead raise the bar for introducing code that relies on built-in COM in the runtime repo (make the warning an error and require going through an exception process, same as if someone wanted to introduce more binary serialization). We've spent several man-months getting rid of built-in COM use in the runtime repo just last year. Does introducing features that make adding more built-in COM into runtime repo easy align with our overall strategy?

**Comment by agocke** [comment] 2022-07-06 03:48
>  Does introducing features that make adding more built-in COM into runtime repo easy align with our overall strategy?

I think so. I don't see any world in which all, or maybe even the vast majority, of code in the runtime repo is safe for trimming. I imagine that we'll continue to add and evolve code that uses built-in COM in perpetuity. Let's try to find the biggest bang for the buck -- what's the most likely cause of the worst failures in the repo? Is preserving COMImport enough to catch these issues? If so, that seems like a simple solution.

**Comment by agocke** [comment] 2022-07-06 03:59
The more I'm thinking about it, I don't think keeping all interfaces when in library mode is a bad solution either.

**Comment by MichalStrehovsky** [comment] 2022-07-06 04:02
> The more I'm thinking about it, I don't think keeping all interfaces when in library mode is a bad solution either.

Yep, it's the only solution that prevents this particular failure mode.

(There will be other failure modes one can get into with COM and trimming. That's why we don't support COM with trimming - because some of them are simply unsolvable.)

**Comment by roji** [comment] 2022-07-06 06:40
> But specifically, it would not kick in for the IResourceManagerShim or IDtcProxyShimFactory interface in @roji's branch because those are not marked as ComImport, but still used with COM. Would this move the needle enough to be useful?

These aren't used in interop in my code base. They were indeed COM interop interfaces in the original C++ shim which I'm now porting to C#, but now just represent plain C# objects. I do think that even doing this for interfaces with `[ComImport]` is useful enough; even if there are some interfaces without it, there's a good likelihood that if an explicit error is thrown for some `[ComImport]` interface, that would bring it to the user's attention and from that point they're aware of it.

But of course, if you're considering not trimming interfaces at all in libraries (for other reasons) that would also take care of it.

> (There will be other failure modes one can get into with COM and trimming. That's why we don't support COM with trimming - because some of them are simply unsolvable.)

Not supporting COM with trimming is one thing, but IMHO the question is what happens when a user does happen to do it (because they're not aware)... I can only stress how frustrating it was to lose days over something which was impossible to diagnose without the help of @AaronRobinsonMSFT.

BTW unless I'm mistaken we're considering aggressively trimming console applications by default for 7.0. If that happens, won't console applications which happen to do COM break in this same, undiagnosable way?

**Comment by MichalStrehovsky** [comment] 2022-07-06 06:50
> I do think that even doing this for interfaces with [ComImport] is useful enough; even if there are some interfaces without it, there's a good likelihood that if an explicit error is thrown for some [ComImport] interface

There would be no error. We would keep members on ComImport interfaces (making this work at runtime), and strip members on other interfaces (making this fail with inscrutable failures modes). It would not fix the general issue - just your particular use case.

> BTW unless I'm mistaken we're considering aggressively trimming console applications by default for 7.0. If that happens, won't console applications which happen to do COM break in this same, undiagnosable way?

Built-in COM is completely disabled within the runtime when PublishTrimmed is active. Users will get a message asking them to not do that if they still try.

This problem is limited to the runtime repo where the libraries team wants to trim (because they don't want to maintain `#defines` for code that is active only in some configurations and dead code in others), but also COM might be used. It's an unsupportable combination in general. Small fixes can be made, but it will never reliably work because trimming removes things and COM/native code might expect them to be still there.

**Comment by MichalStrehovsky** [comment] 2022-07-06 07:18
I think we should do it for all interfaces. Maybe we could look at `ComVisible(false)`, but I suspect it won't amount to any savings and it's not worth the implementation complexity. Running trimming in the unsupported configuration where built-in COM is possible is a support cost and we should optimize for minimizing the support cost.

The libraries team can use `#ifdef`s to remove more unreachable code in this space if needed. Either that, or steer away from built-in COM. Basically, one can't have the cake and eat it too.

**Comment by vitek-karas** [comment] 2022-07-06 11:51
If we add the recent issues we've had with trimming of static interfaces in library mode (which is relatively tricky as well) I'm also inclined to simply keep all interfaces in library mode. We should measure the impact on the size of framework, but I don't expect it to be big.

Alternative would be to disable trimming on some assemblies in runtime repo (most of them make basically no impact on size), but that's probably harder to maintain.

**Comment by AaronRobinsonMSFT** [comment] 2022-07-06 15:12
> Thanks for clarifying that. I still think that fixing this at least where [ComImport] is specified is useful - that was definitely my use case, and I suspect it would be the common case for people running into this problem.

It is by far the most impactful case. The case where a user is passing a .NET implemented COM server is far less interesting. The reason being in that direction the user has control of their code and can set breakpoints in managed code and have a chance of understanding what is going on. There is indeed still an issue with this and one that is complicated but if the interface is marked as `ComImport` it is unambiguous the type is COM and shouldn't be touched. For all non-COM interfaces this isn't as much of a concern because the only real scenario in practice is `IDispatch` - which is non-existent as a new scenario or implementing a COM server which is very special and not something you will get very far with the trimmer anyways.

The consuming part is by far the most impactful and one I'd like to see mitigated in some way. The above suggestions seem more than necessary but I don't know all the complexity here so I defer to you all.

**Comment by MichalStrehovsky** [comment] 2022-07-06 20:26
> The case where a user is passing a .NET implemented COM server is far less interesting.

What's the failure mode if the trimming removes an uncalled interface member in that case?

**Comment by AaronRobinsonMSFT** [comment] 2022-07-06 22:03
> > The case where a user is passing a .NET implemented COM server is far less interesting.
> 
> What's the failure mode if the trimming removes an uncalled interface member in that case?

If the proposal to never touch interfaces marked with `ComImport` (i.e., `import` TypeAttribute flag, ECMA-335 II.23.1.15) is adopted, then technically nothing because the implemented interface will always be correct for the interop scenario. Interfaces not marked with `ComImport` could be pruned but their definition in COM, we no longer generated TLB definitions on the fly, would also need to be update otherwise undefined behavior.

The current state is undefined for all cases.

What I am trying to convey is that interfaces marked with `ComImport` are not .NET interfaces, they are COM interfaces projected into .NET. Interfaces without `ComImport` are .NET interfaces that may be presented to COM. However, those interfaces will also need a corresponding COM definition (e.g., IDL, C/C++, TLB, etc.). Since the runtime no longer has the built-in TLB generation, users in .NET Core 3.1/.NET 5+ must manually define the .NET interfaces in COM and thus know there is a contract to satisfy from .NET. This means they would likely be starting from a .NET app that doesn't have COM disabled. Conversely if a user introduces a `ComImport` interface into their application then they are signing up to use COM implicitly and the trimmer shouldn't assume it can touch that type because I can always write a P/Invoke to `CoCreateInstance` and use APIs that are completely known if `ComImport` is respected.

**Comment by MichalStrehovsky** [comment] 2022-07-07 00:23
What I wanted to hear is that if there is an interface not marked as ComImport, the user uses it with COM, and we stripped a member on it, it leads to undefined behaviors because it won't match the native counterpart and random methods will get called. Is that a correct interpretation?

From what you wrote above:

> Over the past 2 years I've spent at least a week's worth of time investigating these issues and the other interop team members have spent their own time investigating these failures too. This was hit by a dev on the runtime team and if the fix is simple, which is seems to be, we should endevour to make explicit failures rather than illicit undefined behavior.

We have a fix avenue that can fix the undefined behavior for both ComImport and non-ComImport and the fix is simple. Anyone hitting it would cost the interop team investigation time. I'm trying to prevent pain being inflicted on interop team - or am I wrong in the first paragraph of this comment?

We could scope it down to just the ComImport ones if this causes major size regression in the framework, but we don't know that. There's only one customer for this special mode of trimming where this codepath would be activated and that's the runtime repo. I would only consider the partial fix if the data says the full fix is too costly from size perspective. Then we can say "sorry, we tried to prevent inflicting pain on interop team, but we couldn't".

**Comment by agocke** [comment] 2022-07-07 00:38
I should note -- this isn't the only situation where we've second guessed if trimming interfaces in library mode is the right decision. That also makes me think that not doing that is a reasonable path.

To me the biggest risk isn't size, it's actually that we create a bug where we don't trim interfaces correctly in app mode and miss it because we don't trim interfaces at all in library mode, and that was the only place we had a test. Overall that doesn't concern me too much because I think we should get more testing of app mode in general.

**Comment by AaronRobinsonMSFT** [comment] 2022-07-07 00:48
> Is that a correct interpretation?

Yes.

> I'm trying to prevent pain being inflicted on interop team - or am I wrong in the first paragraph of this comment?

No, you are correct. The point though is if someone uses a .NET interface not marked with `ComImport` they must be explicitly projecting the .NET type system into the COM type system. However, if they only implement or consume interfaces with `ComImport` then we are abiding by the COM rules and not imposing anything. The both directions fix isn't really the problem, because in one case you are expanding the COM type system and in the other just consuming it. Consuming it is far more impactful than expanding it in .NET Core.

> That also makes me think that not trimming interfaces is a reasonable path.

That is also fine, all I am stating is the projection of .NET interfaces into COM is far rarer and not something that is a growing concern. However, consuming COM interfaces is still the flavor of the day on Windows.

**Closed as completed** 2022-07-12 18:27 UTC
