### ISSUE TITLE
TrimMode=Link fails with IL2008 error

### ISSUE THREAD

**Issue by JamesNK** [mono/linker#1467] opened 2020-09-01 09:26 UTC
1. Clone https://github.com/grpc/grpc-dotnet
2. Change TargetFramework in `examples\Greeter\Client\Client.csproj` to net5.0.
3. In `examples\Greeter\Client` run `dotnet publish -c Release -r win10-x64 -p:PublishTrimmed=True -p:TrimMode=Link`

Output:

```
C:\Development\Source\grpc-dotnet\examples\Greeter\Client [master ≡ +1 ~2 -0 !]> dotnet publish -c Release -r win10-x64 -p:PublishTrimmed=True -p:TrimMode=Link
Microsoft (R) Build Engine version 16.8.0-preview-20429-01+d58e2b786 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Development\Source\grpc-dotnet\examples\Greeter\Client\Client.csproj (in 246 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Client -> C:\Development\Source\grpc-dotnet\examples\Greeter\Client\bin\Release\net5.0\win10-x64\Client.dll
resource System.Private.CoreLib.xml in System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e : error IL2008: Could not resolve type 'System.Char8' [C:\Development\Source\grpc-dotnet\examples\Greeter\Client\Client.csproj]
resource System.Private.CoreLib.xml in System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e : error IL2008: Could not resolve type 'System.Utf8String' [C:\Development\Source\grpc-dotnet\examples\Greeter\Client\Client.csproj]
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20431.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [C:\Development\Source\grpc-dotnet\examples\Greeter\Client\Client.csproj]
```

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20431.3
 Commit:    1705c68f58
```

**Comment by MichalStrehovsky** [comment] 2020-09-01 09:29
Looks like dotnet/runtime#41654 except the warning is an error here.

(The problem is in the XML file embedded in CoreLib.)

**Comment by JamesNK** [comment] 2020-09-01 09:51
Yeah, it looks like the same bug to me. I changed warnings as errors to false and it completes.

Follow up question: Should `dotnet publish -c Release -r win10-x64 /p:PublishTrimmed=True /p:TrimMode=Link /p:PublishSingleFile=True /p:IncludeNativeLibrariesInSingleFile=True` just produce an exe + pdb?

I followed the instructions [here](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#user-experience) and `IncludeNativeLibrariesInSingleFile` doesn't appear to work. I get native files in the publish directory.

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/09/2020  9:48 PM        5567999 Client.exe
-a---           1/09/2020  9:48 PM          12880 Client.pdb
-a---          30/08/2020 11:00 PM         748936 clrcompression.dll
-a---          30/08/2020 11:00 PM        1323904 clrjit.dll
-a---          30/08/2020 11:00 PM        5154184 coreclr.dll
-a---          30/08/2020 10:56 PM        1042800 mscordaccore.dll
```

**Comment by marek-safar** [comment] 2020-09-01 10:29
Closing as duplicate of dotnet/runtime#41654. Please report single file issue at dotnet/runtime

**Closed by marek-safar** 2020-09-01 10:29 UTC

**Comment by vitek-karas** [comment] 2020-09-01 12:53
The single-file option to include native files in the bundle is now called `IncludeNativeLibrariesForSelfExtract`. As the name suggests (that's why we changed it) - it will cause the executable to extract those files on startup - which comes with a cost and potential complexities around cleanup and such.
